/**
 * Locale-independent values: env-derived config, geometry, and the shape of
 * the nav (ids + SectionId). Actual page copy lives in ./id.ts and ./en.ts —
 * see ./types.ts for the Copy shape and src/lib/locale.tsx for how a
 * component reads the active locale's copy.
 *
 * Unresolved values are read from env so nothing is invented in source. See
 * .env.example — shipping with the fallbacks still in place is a known gap.
 */

const env = import.meta.env;

/** Placeholder. Needs the real WebGIS URL before launch. */
export const MAP_URL_FALLBACK = "#fitur";
/** Placeholder address — confirm before shipping. */
export const CONTACT_EMAIL_FALLBACK = "halo@pathrix.id";

export const ctaUrl: string = env.VITE_MAP_URL || MAP_URL_FALLBACK;
export const contactEmail: string = env.VITE_CONTACT_EMAIL || CONTACT_EMAIL_FALLBACK;
/** When empty the form falls back to composing a mailto: — never a fake success. */
export const contactEndpoint: string = env.VITE_CONTACT_ENDPOINT || "";

export const mapUrlIsPlaceholder = ctaUrl === MAP_URL_FALLBACK;
export const emailIsPlaceholder = contactEmail === CONTACT_EMAIL_FALLBACK;

export const navLinks = [
  { id: "beranda" },
  { id: "cara-kerja" },
  { id: "fitur" },
  { id: "kontak" },
] as const;

export type SectionId = (typeof navLinks)[number]["id"];

/**
 * Placeholder artwork, not a real screenshot. Generated by scripts/art/ and
 * encoded by scripts/encode-images.sh. `src` is a base path without extension;
 * ImageSlot derives .webp and .jpg from it. Swap in the real capture when the
 * product is shippable — nothing else needs to change. Locale-independent
 * geometry only; caption/note/alt live in ./id.ts and ./en.ts.
 */
export const productShot = {
  id: "pathrix-webgis",
  width: 1600,
  height: 900,
  src: "/img/webgis",
} as const;

/*
 * The four field-survey photos that used to sit below the feature grid are
 * gone. They were generated art of trotoar/halte/penyeberangan/stasiun —
 * evidence for the earlier walkability-scoring product, not for the andong and
 * becak pangkalan this PRD actually surveys. Presenting the wrong product's
 * fabricated photographs as "Foto survei lapangan" was the risk; the survey
 * itself is still claimed, in feature 05 above, where it is true.
 * The generated files remain in public/img/field-*.{jpg,webp} and their source
 * in scripts/art/fields.py, unreferenced, should real survey imagery replace
 * them later.
 */
