/**
 * Locale-independent values: env-derived config, geometry, and the shape of
 * the nav (ids + SectionId). Actual page copy lives in ./id.ts and ./en.ts —
 * see ./types.ts for the Copy shape and src/lib/locale.tsx for how a
 * component reads the active locale's copy.
 *
 * Unresolved values are read from env so nothing is invented in source. See
 * .env.example — shipping with the fallbacks still in place is a known gap.
 */

const env = import.meta.env;

/** Placeholder. Needs the real WebGIS URL before launch. */
export const MAP_URL_FALLBACK = "#fitur";
/** Placeholder address — confirm before shipping. */
export const CONTACT_EMAIL_FALLBACK = "halo@pathrix.id";

export const ctaUrl: string = env.VITE_MAP_URL || MAP_URL_FALLBACK;
export const contactEmail: string = env.VITE_CONTACT_EMAIL || CONTACT_EMAIL_FALLBACK;
/** When empty the form falls back to composing a mailto: — never a fake success. */
export const contactEndpoint: string = env.VITE_CONTACT_ENDPOINT || "";

export const mapUrlIsPlaceholder = ctaUrl === MAP_URL_FALLBACK;
export const emailIsPlaceholder = contactEmail === CONTACT_EMAIL_FALLBACK;

export const navLinks = [
  { id: "beranda" },
  { id: "cara-kerja" },
  { id: "fitur" },
  { id: "kontak" },
] as const;

export type SectionId = (typeof navLinks)[number]["id"];

/** Proper nouns — same in both locales. Source: Proposal Pathrix, Lampiran 1 & Kelayakan Teknis. */
export const team = [
  "Muhammad Zakiyyuddin Abdul Adhiim",
  "Nuha Nihaya Shafa",
  "Adnan Abdul Majid",
  "Amrique Marwatul Wafiroh",
  "Meykel Prih Hinoke",
] as const;

/** Proper nouns — same in both locales. Source: Proposal Pathrix, "Persyaratan Teknis". */
export const techStack = [
  "React",
  "MapLibre GL JS",
  "FastAPI",
  "LangGraph",
  "PostgreSQL/PostGIS",
  "GeoPandas · OSMnx · NetworkX",
  "Docker",
] as const;

/**
 * Placeholder artwork, not a real screenshot. Generated by scripts/art/ and
 * encoded by scripts/encode-images.sh. `src` is a base path without extension;
 * ImageSlot derives .webp and .jpg from it. Swap in the real capture when the
 * product is shippable — nothing else needs to change. Locale-independent
 * geometry only; caption/note/alt live in ./id.ts and ./en.ts.
 */
export const productShot = {
  id: "pathrix-webgis",
  width: 1600,
  height: 900,
  src: "/img/webgis",
} as const;

/**
 * CaraKerja's three step photos — curated raster JPGs
 * (scripts/art/photos/carakerja-0{1,2,3}.jpg), encoded by
 * scripts/encode-images.sh. Portrait card-width images (~700px), not the
 * full-bleed product shot above. Order matches `caraKerja.steps` in
 * ./id.ts / ./en.ts. (Superseded the earlier hand-authored SVG placeholders.)
 */
export const caraKerjaShots = [
  { id: "carakerja-01", width: 700, height: 1043, src: "/img/carakerja-01" },
  { id: "carakerja-02", width: 700, height: 470, src: "/img/carakerja-02" },
  { id: "carakerja-03", width: 700, height: 470, src: "/img/carakerja-03" },
] as const;

/**
 * Fitur grid item photos — curated raster JPGs (scripts/art/photos/fitur-*.jpg),
 * encoded by scripts/encode-images.sh. Bento-card-width images (~900px). Order
 * matches the Fitur items in ./id.ts / ./en.ts.
 */
export const fiturShots = [
  { id: "multimoda", width: 900, height: 1341, src: "/img/fitur-multimoda" },
  { id: "ai-agent", width: 900, height: 1341, src: "/img/fitur-ai-agent" },
  { id: "plain-language", width: 900, height: 1341, src: "/img/fitur-plain-language" },
  { id: "multistop", width: 900, height: 1341, src: "/img/fitur-multistop" },
  { id: "firstlastmile", width: 900, height: 1341, src: "/img/fitur-firstlastmile" },
  { id: "sustainability", width: 900, height: 604, src: "/img/fitur-sustainability" },
] as const;

/**
 * Audiens persona photos — curated raster JPGs (scripts/art/photos/audiens-*.jpg),
 * encoded by scripts/encode-images.sh. Persona-card-width images (~800px).
 * Order matches the Audiens groups in ./id.ts / ./en.ts.
 */
export const audiensShots = [
  { id: "mahasiswa", width: 800, height: 537, src: "/img/audiens-mahasiswa" },
  { id: "wisatawan", width: 800, height: 537, src: "/img/audiens-wisatawan" },
  { id: "pekerja", width: 800, height: 537, src: "/img/audiens-pekerja" },
  { id: "pemerintah", width: 800, height: 537, src: "/img/audiens-pemerintah" },
  { id: "umkm", width: 800, height: 537, src: "/img/audiens-umkm" },
] as const;

/**
 * Penutup closing section's full-bleed background photo — curated raster JPG
 * (scripts/art/photos/penutup.jpg), encoded by scripts/encode-images.sh.
 * Rendered up to ~1400-1600px wide on desktop; encoded at 1800px for retina.
 */
export const penutupShot = {
  id: "penutup",
  width: 1800,
  height: 1208,
  src: "/img/penutup",
} as const;

