/**
 * All page copy, verbatim from the design prototype (Pathrix.dc.html).
 * Indonesian throughout; the tagline is the one English string.
 *
 * Unresolved values are read from env so nothing is invented in source. See
 * .env.example — shipping with the fallbacks still in place is a known gap.
 */

const env = import.meta.env;

/** Placeholder. Needs the real WebGIS URL before launch. */
export const MAP_URL_FALLBACK = "#fitur";
/** Placeholder address — confirm before shipping. */
export const CONTACT_EMAIL_FALLBACK = "halo@pathrix.id";

export const ctaUrl: string = env.VITE_MAP_URL || MAP_URL_FALLBACK;
export const contactEmail: string = env.VITE_CONTACT_EMAIL || CONTACT_EMAIL_FALLBACK;
/** When empty the form falls back to composing a mailto: — never a fake success. */
export const contactEndpoint: string = env.VITE_CONTACT_ENDPOINT || "";

export const mapUrlIsPlaceholder = ctaUrl === MAP_URL_FALLBACK;
export const emailIsPlaceholder = contactEmail === CONTACT_EMAIL_FALLBACK;

export const tagline =
  "WebGIS-Based AI Agent for Intelligent Multimodal Mobility in Yogyakarta";

export const heroSubline = "Kota Yogyakarta · Simpul Transit · Indeks TOD";

export const navLinks = [
  { id: "beranda", label: "Beranda" },
  { id: "cara-kerja", label: "Cara Kerja" },
  { id: "fitur", label: "Fitur" },
  { id: "kontak", label: "Kontak" },
] as const;

export type SectionId = (typeof navLinks)[number]["id"];

export const masalah = {
  eyebrow: "Masalahnya",
  heading: "Pindah moda di Yogyakarta jaraknya dekat. Rasanya jauh.",
  paraOne:
    "Turun dari kereta, lanjut naik bus, sisanya jalan kaki. Di atas peta jaraknya cuma beberapa ratus meter — tapi tanpa trotoar yang utuh, penyeberangan yang aman, dan peneduh, potongan terakhir itulah yang membuat orang memilih kembali ke sepeda motor.",
  // Second paragraph carries an inline underlined emphasis, so it is split
  // around it rather than stored as one string.
  paraTwo: {
    before: "Perencana kota tahu masalah ini ada. Yang sulit adalah menunjukkan ",
    emphasis: "di mana persisnya",
    after: ", dan simpul mana yang harus dibenahi lebih dulu. Pathrix menjawab dua pertanyaan itu.",
  },
} as const;

export const caraKerja = {
  eyebrow: "Cara Kerja",
  heading: "Dari lapangan ke keputusan, dalam tiga langkah.",
  steps: [
    {
      index: "01",
      title: "Kumpulkan data",
      body: "Foto survei trotoar, jalur transit, titik halte dan stasiun, sampai ulasan warga — semuanya ditarik jadi satu basis data spasial yang bisa ditelusuri.",
      accent: "lift",
    },
    {
      index: "02",
      title: "AI menilai",
      body: "Computer vision membaca kualitas pedestrian dari foto, NLP membaca keluhan warga, lalu tiap simpul dinilai lintas dimensi TOD dan dibandingkan satu sama lain.",
      accent: "lift",
    },
    {
      index: "03",
      title: "Keputusan siap pakai",
      body: "Hasilnya bukan tumpukan tabel. Peta prioritas menunjukkan simpul mana yang paling butuh perbaikan, dan intervensi apa yang paling berdampak di sana.",
      accent: "warm",
    },
  ],
} as const;

export const fitur = {
  eyebrow: "Fitur",
  heading: "Satu layar untuk melihat, bertanya, dan memutuskan.",
  ctaLabel: "Buka peta",
  items: [
    {
      index: "01",
      title: "Peta multimoda",
      body: "Trans Jogja, jalur kereta, terminal, dan titik antarmoda dalam satu peta yang bisa dinyalakan per lapisan.",
      accent: "lift",
    },
    {
      index: "02",
      title: "Panel AI per simpul",
      body: "Klik satu halte atau stasiun, dapat ringkasan kondisinya dan daftar hal yang paling perlu dibenahi di sana.",
      accent: "lift",
    },
    {
      index: "03",
      title: "Tanya bahasa sehari-hari",
      body: "“Halte mana yang paling sulit dijangkau pejalan kaki?” — dijawab langsung sebagai sorotan di peta.",
      accent: "lift",
    },
    {
      index: "04",
      title: "Jangkauan jalan kaki",
      body: "Lihat area yang benar-benar terlayani dalam waktu jalan kaki yang nyaman — bukan lingkaran ideal di atas kertas.",
      accent: "lift",
    },
    {
      index: "05",
      title: "Walkability dari foto",
      body: "Model computer vision membaca trotoar, penyeberangan, dan peneduh langsung dari foto survei lapangan.",
      accent: "lift",
    },
    {
      index: "06",
      title: "Suara pengguna",
      body: "Ulasan dan keluhan warga dibaca sebagai sentimen per lokasi, jadi data lapangan punya konteks manusia.",
      accent: "warm",
    },
  ],
  fieldLabel: "Foto survei lapangan",
} as const;

/**
 * Real assets do not exist yet. `src` stays null until they are supplied, and
 * the slot renders a flat block with the caption — no shimmer, no skeleton.
 */
/**
 * Placeholder artwork, not a real screenshot. Generated by scripts/art/ and
 * encoded by scripts/encode-images.sh. `src` is a base path without extension;
 * ImageSlot derives .webp and .jpg from it. Swap in the real capture when the
 * product is shippable — nothing else needs to change.
 */
export const productShot = {
  id: "pathrix-webgis",
  caption: "Screenshot WebGIS Pathrix",
  alt: "Antarmuka WebGIS Pathrix: peta simpul transit Yogyakarta dengan panel lapisan, kolom tanya bahasa sehari-hari, dan panel penilaian AI untuk satu simpul.",
  width: 1600,
  height: 900,
  src: "/img/webgis",
} as const;

/** Placeholder survey imagery, same arrangement as productShot above. */
export const fieldPhotos = [
  {
    id: "pathrix-field-1",
    caption: "Foto trotoar",
    alt: "Trotoar yang terputus di dekat simpul transit: paving hilang, tanah terbuka, dan tiang utilitas berdiri di tengah jalur pejalan kaki.",
    src: "/img/field-1",
  },
  {
    id: "pathrix-field-2",
    caption: "Foto halte",
    alt: "Halte Trans Jogja dengan atap peneduh, bangku, dan papan rute di tepi trotoar berpaving pemandu.",
    src: "/img/field-2",
  },
  {
    id: "pathrix-field-3",
    caption: "Foto penyeberangan",
    alt: "Penyeberangan zebra yang catnya sudah pudar tanpa pelindung penyeberangan, dengan sepeda motor berhenti di atas marka.",
    src: "/img/field-3",
  },
  {
    id: "pathrix-field-4",
    caption: "Foto stasiun",
    alt: "Bagian depan stasiun dengan kanopi peron, garis batas aman kuning, dan calon penumpang menunggu di peron.",
    src: "/img/field-4",
  },
] as const;

/** Rendered size of each field photo (4:5). Used to reserve layout. */
export const FIELD_PHOTO_SIZE = { width: 640, height: 800 } as const;

export const kontak = {
  eyebrow: "Kontak",
  heading: "Mari benahi simpul transit Yogyakarta bersama.",
  body: "Pathrix dibangun untuk dipakai orang yang benar-benar mengambil keputusan — dinas perhubungan, badan perencanaan, kampus, dan komunitas pejalan kaki. Kalau kamu salah satunya, kami ingin dengar.",
  emailLabel: "Surel",
  fields: {
    nama: { label: "Nama", placeholder: "Nama kamu" },
    kontak: { label: "Surel atau instansi", placeholder: "nama@instansi.go.id" },
    pesan: {
      label: "Pesan",
      placeholder: "Kawasan atau simpul mana yang ingin kamu bahas?",
    },
  },
  submitLabel: "Kirim pesan",
  submitSentLabel: "Terkirim",
} as const;

export const footer = {
  competition: "MAPID WebGIS Competition 2026",
} as const;
